### ISSUE TITLE
[BUG] GPU 메모리 부족 문제

### ISSUE THREAD

**Issue by Smk369** [bareun-nlp/bareun-support#10]
![image](https://github.com/bareun-nlp/bareun-support/assets/93764295/e1b3f1bc-35f0-4e61-a4fa-972f4b3131cd)

![image](https://github.com/bareun-nlp/bareun-support/assets/93764295/cd4d5a03-d2cc-4307-b859-a6e74ba4cdc4)

RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[1573840,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc라는 코드와 함께 작동이 안 됩니다.
이러한 문제가 자꾸 발생하네요. 
GPU 메모리는 8기가인데, 바른 형태소 분석기를 돌리기엔 이 메모리 용량이 부족한가요? 
검색해보니 배치 사이즈를 줄이라는데...
배치 사이즈를 줄이는 방법이 있나요?

**Comment by YugwonWon** [comment]
* 문장 개수로 배치 사이즈 조절하기 
  * GPU 메모리에는 한계가 있으므로 배치 사이즈가 크면 OOM 에러가 발생합니다.  
  * 현재 배치사이즈는 문장의 new line('\n')으로 구분된 문장이라면 그 개수만큼 배치크기가 들어갑니다. 
  * 만약 new line이 없다면 내부처리 로직에 따라서 최대 글자수를 기준으로 문장이 잘리게 됩니다. 
  * 일반적으로 500 문장까지는 한 배치로 처리가 가능한 것으로 확인됩니다만, 그 이상은 메모리부족 현상이 일어날 수 있습니다. 따라서 너무 긴 문장을 호출하셨다면 가능하면 500문장 이내로 join 된 문장을 한 번의 요청으로 부탁드립니다.
* TF_FORCE_GPU_ALLOW_GROWTH=true 옵션 설정
  * Tensorflow에서 GPU 사용량을 동적으로 활성화하는 설정이 있습니다. 이 옵션은 GPU 메모리를 사용할 때 필요한 만큼의 전체 메모리를 할당하지 않고, 할당을 시작할 때 필요한 메모리만 할당하고, 메모리를 동적으로 할당하도록 허용합니다.  이 옵션으로 좀 더 여유있게 메모리를 관리할 수 있게 됩니다.
  * 윈도우라면 시스템 환경 변수(Environment Variables)메뉴에서 시스템 변수(System variables)에 New(New System Variable)를 누르시고, Variable name에 `TF_FORCE_GPU_ALLOW_GROWTH` 그리고 Variable value에 `true`를 넣고 OK 저장하시면 됩니다.
