### ISSUE TITLE
[BUG] 배포에 관한 문의

### ISSUE THREAD

**Issue by breakoutson** [bareun-nlp/bareun-support#11]
무료 API 사용시 제품을 다운로드 받은 본인만 사용할 수 있는 것인가요?
아니면 API를 활용해 만든 프로그램을 제3자에게 배포도 가능한가요?

**Comment by gih2yun** [comment]
@breakoutson 님, 본인이 연구 목적으로 사용해도 되고, 이를 이용해서 다른 사람들이 쓸 수 있도록 만드셔도 됩니다.

다만, 이 프로그램을 통해서 수익이 발생하거나 기관의 서비스로 사용된다면, 이에 대해서는 과금을 하는 정책입니다.
