### ISSUE TITLE
[BUG] 홈페이지 오타

### ISSUE THREAD

**Issue by joelkim** [bareun-nlp/bareun-support#15]
**버그에 대한 설명**
홈페이지에 오타가 있습니다.

**버그 발생 재현**
- 홈페이지 형태소 분석 사용해보기 화면 
- https://bareun.ai/demo/analyze

**예상 결과**
"텍스트을 입력하세요" -> "텍스트를 입력하세요"

**화면 스크린샷**
![image](https://github.com/bareun-nlp/bareun-support/assets/523603/1b940552-2dcb-4800-b796-ed971669f4a0)

**Comment by gih2yun** [comment]
@joelkim 알려주셔서 감사합니다.

**Comment by YugwonWon** [comment]
* 수정 완료했습니다. 감사합니다.

![image](https://github.com/bareun-nlp/bareun-support/assets/107927220/25adad98-1cea-4393-9df7-746b27f84f0c)
