### ISSUE TITLE
[BUG] colab 소켓 닫힘 문제

### ISSUE THREAD

**Issue by juyeon6273** [bareun-nlp/bareun-support#16]
**버그에 대한 설명**
colab에서 InactiveRpcError of RPC가 발생합니다. gRPC 서버가 localhost:5656에서 실행되고 있지 않습니다. 
바른 사이트에서 '구글 코랩에서 사용하기' 방법으로 시도했습니다.

**버그 발생 재현**
버그 발생의 단계:
new_content = data['content'].values
res = t.tags(new_content)
m = res.msg()
tf.PrintMessage(m, out=sys.stdout, as_utf8=True)
를 실행하면 다음과 같은 에러가 발생합니다.

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:5656: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:5656: Failed to connect to remote host: Connection refused {created_time:"2023-10-09T08:14:03.767136743+00:00", grpc_status:14}"

**예상 결과**
다음과 같은 분석 결과를 출력하고 싶습니다.
sentences {
    text {
        content: "안녕하세요. 정말 좋은 날씨네요. 오늘도 힘내요."
        length: 27
    }
    tokens {
        text {
        content: "안녕하세요."
...
}

**화면 스크린샷**
![스크린샷 2023-10-09 172845](https://github.com/bareun-nlp/bareun-support/assets/106322912/14a006fb-508b-4795-9b13-87a1da0fa4ee)

**
 - colab, python
 
 ** 파일
[socket_error.zip](https://github.com/bareun-nlp/bareun-support/files/12843946/socket_error.zip)

**Comment by juyeon6273** [comment]
.

**Comment by gih2yun** [comment]
@juyeon6273 `바른` 서비스가 실행되지 않았던 문제로 보입니다.

잘 해결하신 것으로 보여 다행입니다.

질문해주셔서 감사합니다.
