### ISSUE TITLE
[BUG]JAVA 예제 소스에 수정이 필요하겠네요.

### ISSUE THREAD

**Issue by JuseokYun** [bareun-nlp/bareun-support#18]
**버그에 대한 설명**
버그에 대한 명확하고 간결한 설명을 부탁드립니다.
오류가 발생한 API 서비스 및 버전을 말씀해주세요.

**버그 발생 재현**
버그 발생의 단계:
1. '...' 으로 이동합니다.
2. '....' 을 클릭 또는 호출합니다.
3. 오류 발생

**예상 결과**
기대하는 결과에 대한 명확하고 간결한 설명을 부탁드립니다.

**화면 스크린샷**
가능한 경우, 문제를 설명하는데 도움이 되는 스크린샷을 추가합니다.

**데스크탑 (다음의 정보를 입력해주세요.):**
 - OS: [예시. Ubuntu 22.10]
 - Browser, Language [예시. chrome, python]
 - Version [예시 22, 3.7]

**Comment by JuseokYun** [comment]
버그는 아닙니다. 

기본적으로 제공되는 설명 창에서 
JAVA 쪽 예제 소스에서 나오는 선언부분에

import bareun.ai.AnalyzeSyntaxRequest;
import bareun.ai.AnalyzeSyntaxResponse;
import bareun.ai.CustomDictionary;
import bareun.ai.CustomDictionaryMeta;
import bareun.ai.Document;
import bareun.ai.LanguageServiceGrpc;

이렇게 나오네요. 

Git에 올라온 자료를 참고해 수정해서 사용하고 있긴합니다.

**Comment by gih2yun** [comment]
알려주셔서 감사합니다.

**Comment by gih2yun** [comment]
@YugwonWon markdown overview.md java 예제에서 

bareun.ai -> ai.bareun 으로 변경
