### ISSUE TITLE
[BUG] 윈도우 GPU 메모리 점유 관련

### ISSUE THREAD

**Issue by syubi96** [bareun-nlp/bareun-support#19]
**버그에 대한 설명**
기존에는 이상이 없었으나 최근 컴퓨터를 재부팅하면 GPU메모리를 8GB이상 점유하는 알 수 없는
프로그램이 확인되어 점검을 하게 되었습니다.

확인 결과 바른 형태소분석기가 VRAM를 차지하고 있더군요. 이전에는 임의로 실행되어 메모리를 차지하지 않았던 것 같은데
어제 PC 재부팅 이후부터 재부팅시 자동으로 실행되며 VRAM을 점유하는 현상이 확인됩니다.

**버그 발생 재현**
버그 발생의 단계:
1. PC 재부팅

**예상 결과**
간헐적인 바른 프로세스의 자동 실행 및 VRAM 점유

**화면 스크린샷**
가능한 경우, 문제를 설명하는데 도움이 되는 스크린샷을 추가합니다.

**데스크탑 (다음의 정보를 입력해주세요.):**
-에디션	Windows 11 Home
-버전	22H2
-설치 날짜	‎2022-‎12-‎10
-OS 빌드	22621.2715
-경험	Windows Feature Experience Pack 1000.22677.1000.0

**Comment by YugwonWon** [comment]
@gih2yun 
네, 안녕하세요. 재부팅시 바른이 자동 실행하도록 되어 있습니다.
정상적이라면 바른은 아래와 같이 gpu를 8GB가 아닌 800MB 정도를 사용합니다.
![image](https://github.com/bareun-nlp/bareun-support/assets/107927220/ad06dd1b-38e6-4fd9-9f42-bed0d458f819)

메모리 점유를 사용하고 싶지 않다면, 서비스를 중지하고 나중에 형태소 분석기를 사용할 때 다시 사용을 하는 것이 좋을 것 같습니다.
'윈도우키(win)+R' 키를 누른 다음, 실행 창이 뜨면 services.msc를 입력합니다(윈도우 검색에 '서비스' 데스크톱 앱입니다). 서비스 창이 실행되고, '바른 한국어 형태소 분석 서비스'를 찾아 우클릭하여 '속성' 메뉴를 선택합니다. '서비스 상태'탭에서 '중지'을 눌러서 바른 서비스를 중지 합니다.  그리고 '시작 유형'을 '수동'으로 설정하면 다음에 사용할 때 수동으로 시작하게 할 수 있을 것입니다.

**Comment by syubi96** [comment]
답변 감사드립니다.

그리고 최근 비디오 메모리 외에도 사용하지 않았지만
자동으로 램을 2기가 가량 차지하는 현상도 있어서 알려드립니다.

![스크린샷 2023-12-14 205603](https://github.com/bareun-nlp/bareun-support/assets/104792427/668cb062-2807-4f38-bb8d-a8e9fde35bfa)

데스크탑 (다음의 정보를 입력해주세요.):
-에디션 Windows 11 Home
-버전 22H2
-설치 날짜 ‎2022-‎12-‎10
-OS 빌드 22621.2715
-경험 Windows Feature Experience Pack 1000.22677.1000.0

**Comment by YugwonWon** [comment]
@syubi96 
네, 알려주셔서 감사합니다.
서비스가 종료되어도 메모리 캐시가 남아 있을 수 도 있을 것 같습니다.
이럴 경우, 프로세스에서 바른을 찾아 '프로세스 끝내기'를 눌러서 종료해주시면 좋을 것 같습니다.

프로그램에서도 원인을 찾아 수정하도록 하겠습니다.
감사합니다.
