### ISSUE TITLE
[문의] 형태소 분석에 대한 문의

### ISSUE THREAD

**Issue by Smk369** [bareun-nlp/bareun-support#20]
안녕하세요? 형태소 분석기 사용 중 문의사항이 있어 연락드립니다.  

           data = f.read()
            reult_list = data.split('.')
            data = 0
            print(reult_list[:20])
            
            for anal in reult_list : 

                ana_data = tagger.tags(anal)
                pa_data = ana_data.pos()
                print("------")
                print(pa_data)
                print("------")

이러한 코드 과정에서, 

['"대통령, 시장 방문만 하지 말고 실천해달라" 2008년의 마지막 새벽, 언론의 카메라는 서울 여의도를 향했다', ' 방송법 등 주요쟁점 법안이 상정될 국회 본회의장을 두고 여야 의원들의 전쟁을 기다리고 있었던 것', ' 같은 시각, 국회 밖 세상에서 서민들은 경제 위기와 강추위 속에서 삶의 고단함과 정치에 대한 절망감에 맞선 채 팍팍한 삶을 이어가고 있었다', ' 이들의 목소리를 듣기 위해 이날 새벽 3시 대한민국의 아침을 여는 서울 가락동 농수산물종합도매시장으로 향했다', ' 가락시장으로 가는 택시 안에서 2008년의 마지막 새벽을 맞는 서민들의 얘기를 엿들을 수 있었다', ' 택시기사 서인철(가명·63)씨는 말한다', ' "LPG값이 휘발유보다 비싸졌고, 9만9000원 하는 사납금 내기도 벅차다', ' (한 달에) 100만원도 벌기 힘들다', ' 40년 동안 택시기사를 했는데, 요즘이 제일 힘들다', ' 택시 손님 열에 아홉은 힘들다고 한다', ' 더 암울한 건 내년엔 더 어렵다는 거다', ' 정치인들? 멱살 잡고 싸우는 거 말고 뭘 하나? 이젠 짜증내기도 귀찮다', '" 치열한 삶터, 가락시장에 드리워진 불황의 그림자 새벽 3시 30분, 가락시장의 첫인상은 그야말로 치열한 삶터였다', " 가락시장 인근 도로엔 농수산물을 싣고 전국에서 올라온 트럭들이 '차산차해'를 이뤘다", ' 가락시장 안에는 트럭과 함께 짐을 옮기는 지게차·오토바이·손수레로 가득 차 더욱 복잡했다', ' 가락시장 수산시장에서는 방어 경매가 한창이었다', ' 중개인이 일반인들이 알아듣기 힘든 말로 몇 차례 중얼거리자 경매는 이내 끝났다', ' 방어는 어찌나 힘이 좋은지 한 번 몸을 뒤집자 바구니 밖 3~4m까지 물이 튈 정도였다', ' 상인들도 방어만큼이나 바삐 움직였다', ' 사람들은 분주히 수산물을 날랐다']
------
[('"', 'SS'), ('대', 'NNB'), ('통', 'NNG'), ('령', 'NNP'), (',', 'SP'), ('시', 'NNG'), ('장', 'NNG'), ('방', 'NNG'), ('문', 'NNG'), ('만', 'NA'), ('하', 'IC'), ('지', 'NA'), ('말', 'NNG'), ('고', 'NA'), ('실', 'NA'), ('천', 'NR'), ('하', 'VV'), ('아', 'EF'), ('달', 'NNG'), ('라', 'NNG'), ('"', 'SS'), ('2', 'SN'), ('0', 'SN'), ('0', 'SN'), ('8', 'SN'), ('년', 'NNB'), ('의', 'JKG'), ('마', 'NA'), ('지', 'NA'), ('막', 'MAG'), ('새', 'NNG'), ('벽', 'NNG'), (',', 'SP'), ('언', 'NA'), ('론', 'NA'), ('의', 'JKG'), ('카', 'NNP'), ('메', 'NNG'), ('라', 'NNG'), ('는', 'JX'), ('서', 'NA'), ('울', 'NA'), ('여', 'NNP'), ('의', 'JKG'), ('도', 'NNG'), ('를', 'JKO'), ('향', 'NNG'), ('하', 'VV'), ('았', 'EP'), ('다', 'MAG')]
------

이러한 값이 나옵니다. 
문장 단위로 형태소 분석을 한 것인데, '대통령'과 같은 것을 대통령/nng로 분석하지 못하거나, '언론'을 언/na, 론/na로 분석하게 되는 것에 이유가 있을까요? 단어 단위를 모두 한글자 단위로 나누어 분석하는 것 같습니다. 이에 대한 해결 방법이 있을까요?

감사합니다.

**Comment by YugwonWon** [comment]
@Smk369 
네, 안녕하세요. tags 함수는 리스트를 받습니다. 여러 개의 문장을 리스트로 저장하여 한 번에 분석하기에 용이합니다.
개별 문자열은 tag 함수를 사용하여야 합니다.
그래서 코드를 수정하면 이렇게 됩니다.

```python
        data = f.read()
        reult_list = data.split('.')
        data = 0
        print(reult_list[:20])
        
        for anal in reult_list : 

            ana_data = tagger.tag(anal) # tags 대신 tag 사용
            pa_data = ana_data.pos()
            print("------")
            print(pa_data)
            print("------")
```

**Comment by Smk369** [comment]
네, 감사합니다. 혹시 한가지 더 여쭤보아도 될까요?
도저히 잘못된 곳을 찾을 수 없어 너무 막막하네요...

import sys
from bareunpy import Tagger
import yaml
import time
from tqdm import tqdm
import os

API_KEY="k**********"


sent_dict = []
time1 = time.time()
with open(r'C:\Users\dse40\OneDrive\바탕 화면\말뭉치\신문 말뭉치 2009~2018\텍스트 파일\09년도.txt', 'r', encoding = 'utf-8') as f:

    time1 = time.time()


    data = f.read()
    reult_list = data.split('.')

    len_lines = len(reult_list)
    print(len_lines)
    num_itters = len_lines//500 + 1 if len_lines%500 != 0 else len_lines//500
    tt = []

    for i in range(num_itters):
        tt.append("".join(reult_list[500*i:500*(i+1)]))


    for text in tqdm(tt):
        res = tagger.tags([text]).msg()
        len_sent = len(res.sentences)
        for idx in range(0, len_sent):
            key = res.sentences[idx].text.content
            sentence = {key: []}      
            for tok in res.sentences[idx].tokens:
                sentence[key].append({
                        "token": tok.text.content,
                        "tag": tok.tagged
                        })
            sent_dict.append(sentence)    


                
elapsed_call_time = time.time() - time1
print(f'elapsed_call_time: {elapsed_call_time:.3f}')
            
            
with open(r'C:\Users\dse40\OneDrive\바탕 화면\말뭉치\신문 말뭉치 2009~2018\형태소 분석 파일\%09년_데이터.yaml', 'w', encoding = 'utf-8') as outfile : 
    yaml.dump(sent_dict, outfile, default_flow_style=False, allow_unicode=True, sort_keys=False)
print('saved output -> test_sentences.yaml')


이와 같이 코드를 사용하는데, 파일이 어디에도 저장되지가 않는 현상이 발생합니다. 

![image](https://github.com/bareun-nlp/bareun-support/assets/93764295/28b9af0d-7d57-44cf-854d-5e4b5c606fce)

코드는 이렇게 정상적으로 작동하는데, 혹시 위 코드에서 잘못된 점이 있을까요?
오류 메시지도 뜨지 않아 갑갑할 따름입니다. 
분명 저의 초보적인 실수 때문인 것 같은데, 알려주신다면 감사하겠습니다.

**Comment by YugwonWon** [comment]
@Smk369 
* 코드에는 문제가 없어 보이는데요. 왜냐하면 위 코드 그대로 아래와 같이 실행했을때 문제가 없기 때문입니다.
* 환경이 윈도우라서 재연해보기 힘들지만, 몇 가지 확인을 좀 해봐야 할 것 같습니다.
* OneDrive 쓰기 권한? 저장을 다른 루트에 해보는 것은 어떨까요? 
  * r'C:\Users\dse40\OneDrive\바탕 화면\말뭉치\신문 말뭉치 2009~2018\형태소 분석 파일%09년_데이터.yaml' 이렇게 절대 경로로 지정하지 말고 그냥 현재 스크립트가 실행되는 루트에 저처럼 파일 이름만 설정해서 저장해서 찾을 수도 있습니다. 
* PyYAML 라이브러리가 제대로 설치 되었을까요?
* 아래 코드는 제가 리눅스에서 위 코드 그대로 재현해본 것입니다. 저장이 잘 됩니다.

```python
import sys
from bareunpy import Tagger
import yaml
import time
from tqdm import tqdm
import os

API_KEY="k**********"

sent_dict = []
time1 = time.time()
tagger = Tagger(API_KEY, 'localhost')
with open("data/word2vec/14대선-야당-김대중-1993년-민주당.txt", 'r', encoding = 'utf-8') as f:
    data = f.read()
    reult_list = data.split('.')

len_lines = len(reult_list)
print(len_lines)
num_itters = len_lines//500 + 1 if len_lines%500 != 0 else len_lines//500
tt = []

for i in range(num_itters):
    tt.append("".join(reult_list[500*i:500*(i+1)]))


for text in tqdm(tt):
    res = tagger.tags([text]).msg()
    len_sent = len(res.sentences)
    for idx in range(0, len_sent):
        key = res.sentences[idx].text.content
        sentence = {key: []}      
        for tok in res.sentences[idx].tokens:
            sentence[key].append({
                    "token": tok.text.content,
                    "tag": tok.tagged
                    })
        sent_dict.append(sentence)    
elapsed_call_time = time.time() - time1
print(f'elapsed_call_time: {elapsed_call_time:.3f}')

with open(f'test_sentences.yaml', 'w', encoding='utf-8') as outfile:
    yaml.dump(sent_dict, outfile, default_flow_style=False, allow_unicode=True, sort_keys=False)
print('saved output -> test_sentences.yaml')

# with open(r'C:\Users\dse40\OneDrive\바탕 화면\말뭉치\신문 말뭉치 2009~2018\형태소 분석 파일%09년_데이터.yaml', 'w', encoding = 'utf-8') as outfile :
#     yaml.dump(sent_dict, outfile, default_flow_style=False, allow_unicode=True, sort_keys=False)
# print('saved output -> test_sentences.yaml')

```

**Comment by Smk369** [comment]
네, 감사합니다. 알려주신대로 진행해보니 문제가 해결되었네요. 항상 빠르고 친절한 답변 감사합니다. ㅎㅎㅎ
