### ISSUE TITLE
[BUG] API 키 등록이 안 됩니다.

### ISSUE THREAD

**Issue by Expectedgun** [bareun-nlp/bareun-support#22]
API 키 등록이 안 됩니다.

http://localhost:5655/
의 경우 사이트 접속이 차단되고, 보안 설정을 통해 '보안 연결 사용'을 해제해도 접속이 안 됩니다.

윈도우 cmd를 통해 API 키를 등록하려고 해도 다음과 같은 코드가 뜨며 등록이 안 되는 듯합니다.

 - window 11
 - chrome
 - 23H2

**Comment by gih2yun** [comment]
cmd를 위 명령을 관리자 권한에서 실행하시면, 일단 파일에 접근할 수 없는 오류가 나타나지 않게 됩니다.

바른은  "상시 서비스"모드로 동작하기 때문에 관리자 권한을 요구합니다. 그래서 명령어를 실행할 때에는 관리자권한으로 해야 합니다.

https://docs.bareun.ai/install/windows/#api 이 링크의 설명이 부족하네요. 이 부분은 수정해서 반영하도록 할게요.

위에서 사이트 접속이 차단된 것은 아마도 bareun의 서버가 정상적으로 실행되지 않은 경우라고 보여집니다. 원인이 다양할 수 있어서 필요한 경우, 기술지원이 필요하실 수도 있습니다. support@bareun.ai 로 메일을 보내주시면, 제가 필요한 경우 원격지원도 해드립니다.

감사합니다.

**Comment by gih2yun** [comment]
키 정보가 들어와서 다행히 다른 사람이 가져가지는 않았지만, 2차 개인 정보에 속하므로 그림은 삭제하시면 좋을 것 같아요.

**Comment by Expectedgun** [comment]
덕분에 관리자권한으로 실행해 API 키 등록을 완료했습니다. 스크린샷 2차 정보는 미처 생각을 못 했네요. 감사합니다.
