### ISSUE TITLE
[BUG] Colab 예시 코드 오류

### ISSUE THREAD

**Issue by ByungjunKim** [bareun-nlp/bareun-support#4]
**버그에 대한 설명**
!dpkg -i bareun-v2.0.0.linux-x86_64.deb

위 명령어 수정이 필요하겠습니다. 2.0.1로 업데이트 되면서 파일명이 바뀌었고, 계속 업데이트 될텐데 초보자에게는 왜 이런지 모를수도 있겠습니다.

**버그 발생 재현**
버그 발생의 단계:
1. '...' 으로 이동합니다.
2. '....' 을 클릭 또는 호출합니다.
3. 오류 발생

**예상 결과**
bareun의 최신 버전.deb 파일명에 대응할 수 있도록 코드 수정

**화면 스크린샷**
가능한 경우, 문제를 설명하는데 도움이 되는 스크린샷을 추가합니다.

**데스크탑 (다음의 정보를 입력해주세요.):**
 - OS: Google Colab
 - Browser, Language [예시. chrome, python]
 - Version [예시 22, 3.7]

**Comment by YugwonWon** [comment]
네 맞습니다! 그래서 버전과 관계 없이 `bareun-linux.deb` 의 이름으로 파일을 받고 설치하도록 예제를 수정하였습니다. 알려주셔서 감사합니다!
