### ISSUE TITLE
[BUG] API 등록이 되지 않습니다.

### ISSUE THREAD

**Issue by joelkim** [bareun-nlp/bareun-support#7]
**버그에 대한 설명**
Mac OSX에서 2.0.1 버전을 설치하였는데 API 등록이 되지 않습니다.

**버그 발생 재현**

```
$ ~/bareun-v2.0.1/bin/bareun -reg <API>
Use config file: /Users/joelkim/bareun-v2.0.1/config/bareun.json
------
500 Internal Server Error
register err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.64.151.240:5654: i/o timeout"
```

**데스크탑 (다음의 정보를 입력해주세요.):**
 - OS: Mac OSX 13.2.1(22D68)
 - Version: bareun 2.0.1

**Comment by gih2yun** [comment]
질문해 주셔서 감사합니다.

현재 API 사용 등록을 하는 서버에는 현재 문제가 없이 잘 동작하고 있습니다.
사용하시는 PC가 외부로 접속하는 방화벽이 막혀있지는 않는지요?

만일 등록하는 포트가 막혀 있다면, 네트워크를 관리하시는 관리자에게 문의해주셨으면 합니다.

해당 포트를 사용할 수 없는 경우에는 저희가 별도로 라이센스 파일을 생성해서 열 수 있도록 하고 있습니다.

**Comment by gih2yun** [comment]
현재까지 라이센스 파일을 만드는 정책은 상용 라이센스에 한해서 `내부망 등에서 쓰는 경우`로만 제약을 하고 있습니다.

빠른 사용을 해보시려면, 상용라이센스를 만들어 드려야 하는 상황입니다.
또 다른 해결 방법은 80/443을 통해서도 처리할 수 있는 방법이 있습니다. 이것은 새 버전을 만들어서 드려야 하는 상황입니다.

하지민, 인터넷 사용이 가능한 조건이고, 방화벽에 의해서 해당 포트가 막혀 있는 경우를 고려하지 못했습니다.

**Comment by joelkim** [comment]
메일을 드렸습니다. 감사합니다. 이 이슈는 닫겠습니다.
