### ISSUE TITLE
빠른 형태소 분석을 위해 GPU를 사용하고 싶습니다.

### ISSUE THREAD

**Issue by ryuken73** [bareun-nlp/bareun-support#9]
안녕하세요. 훌륭한 형태소 분석기를 제공해주셔서 감사합니다. ^^

버그는 아니고 형태소 분석 속도를 높이는 방법을 찾고 있습니다.
GPU를 활용해 보고 싶은데요, 방법 알려주실 수 있으실까요?

**사용환경
  클라이언트 : bareun.js사용
  사용API : Tagger.tag

**데스크탑 (다음의 정보를 입력해주세요.):**
 - OS: Windows10 22H2
 - Version: 2.0.3
 - 그래픽카드: NVIDIA Quadro K6000

**Comment by YugwonWon** [comment]
@ryuken73 
* Tensorflow의 CUDA를 사용하여 GPU를 사용하려면 적절한 CUDA 버전과 cuDNN 라이브러리가 Windows에 설치되어 있어야 합니다.
* 바른 형태소 분석기는 현재 Tensorflow 2.9.1 version을 사용하고 있습니다. 따라서 이에 꼭 맞는 버전을 쓰는 것을 권장합니다(https://www.tensorflow.org/install/source_windows?hl=ko). 
  * cuDNN version : 8.1
    * cuDNN 다운로드 사이트 링크: https://developer.nvidia.com/cudnn  
    * cuDNN을 다운로드 하려면 회원가입이 되어있어야 합니다.
  * CUDA : 11.2 
    * CUDA Toolkit 사이트 링크: https://developer.nvidia.com/cuda-toolkit-archive
  * 최소 그래픽카드 버전 : >=452.39*
    * 그래픽카드 드라이브 다운로드 링크: https://www.nvidia.co.kr/download/Find.aspx?lang=kr
    * 참고자료(https://docs.nvidia.com/deploy/cuda-compatibility/index.html)
* 마지막으로 환경변수를 설정해야 합니다.
  * Windows 시스템 환경 변수 편집 메뉴>Path 변수 편집>
    * `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin`
    * `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include`
    * `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib`
  * 위 경로를 추가하고 적용합니다.

* 추후 공식 매뉴얼로 해당 과정에 대한 자세한 안내를 업데이트하겠습니다. 테스트해 보시고 안되면 말씀해주세요! 감사합니다.

**Comment by YugwonWon** [comment]
* 또한 속도 개선 문제와 관련하여 저희가 지난 번에 작성한 아래 소개된 예제처럼 멀티라인을 이용한다면 더 많은 문장을 동시에 처리할 수 있어 유용합니다.
  * https://github.com/bareun-nlp/bareun-bin/blob/main/samples/colab_bareun_multiline.ipynb

**Comment by ryuken73** [comment]
오!! 감사합니다. 위 멀티라인으로 한번 시도해봐야겠네요~ 

그리고, 알려주신 대로 설정했더니 GPU를 잘 사용합니다. 
GPU사용하지 않았을 때 대비 4배~5배정도 빨라졌습니다. 
감사합니다. ㅎㅎ

다만,  빠르게 추출되는 것을 보고 욕심이 나서 동시작업 숫자를 좀 많이 늘였더니 
아래 처럼 오류가 발생하고 작업이 중지되더군요. "바른"서버가 다운되지는 않고요.

동시작업을 100개로 유지하니까 더이상 오류발생없이 안정적으로 동작하고 있습니다.
 (현재 20분정도 계속 작업중입니다.)
```
Error: 9 FAILED_PRECONDITION: panic: 2 root error(s) found.
  (0) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[2888,8,80,80] and type float on /job:localhost/replica:0/task:
0/device:GPU:0 by allocator GPU_0_bfc
         [[{{function_node __inference__wrapped_model_219229856}}{{node model/transformer_encoder/encoder_layer/multi_head_att
ention/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions fo
r current allocation info. This isn't available when running in Eager mode.
         [[StatefulPartitionedCall/_1799]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions fo
r current allocation info. This isn't available when running in Eager mode.
  (1) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[2888,8,80,80] and type float on /job:localhost/replica:0/task:
0/device:GPU:0 by allocator GPU_0_bfc
         [[{{function_node __inference__wrapped_model_219229856}}{{node model/transformer_encoder/encoder_layer/multi_head_att
ention/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions fo
r current allocation info. This isn't available when running in Eager mode.
0 successful operations.
0 derived errors ignored.
    at callErrorFromStatus (D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\client.js:192:7
6)
    at Object.onReceiveStatus (D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\client-intercep
tors.js:360:141)
    at Object.onReceiveStatus (D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\client-intercep
tors.js:323:181)
    at D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\cli
ent.js:160:34)
    at ServiceClientImpl.<anonymous> (D:\002.Code\002.node\typesense_db2_indexer\node_modules\@grpc\grpc-js\build\src\make-cli
ent.js:105:19)
    at D:\002.Code\002.node\typesense_db2_indexer\node_modules\bareun\src\LanguageServiceClient.js:52:25
    at new Promise (<anonymous>)
    at LanguageServiceClient.asyncAnalyzeSyntax (D:\002.Code\002.node\typesense_db2_indexer\node_modules\bareun\src\LanguageSe
rviceClient.js:51:23)
    at Tagger.tag (D:\002.Code\002.node\typesense_db2_indexer\node_modules\bareun\src\Tagger.js:150:53)
    at getSurfacesWithTag (D:\002.Code\002.node\typesense_db2_indexer\lib\bareunLib.js:8:37)
    at D:\002.Code\002.node\typesense_db2_indexer\read_from_db2.js:68:41
    at Array.map (<anonymous>)
    at BareunWorker.getSurfaces (D:\002.Code\002.node\typesense_db2_indexer\read_from_db2.js:68:30) {
  code: 9,
  details: 'panic: 2 root error(s) found.\n' +
    '  (0) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[2888,8,80,80] and type float on /job:localhost/replica:0/
task:0/device:GPU:0 by allocator GPU_0_bfc\n' +
    '\t [[{{function_node __inference__wrapped_model_219229856}}{{node model/transformer_encoder/encoder_layer/multi_head_atte
ntion/MatMul}}]]\n' +
    "Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptio
ns for current allocation info. This isn't available when running in Eager mode.\n" +
    '\n' +
    '\t [[StatefulPartitionedCall/_1799]]\n' +
    "Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptio
ns for current allocation info. This isn't available when running in Eager mode.\n" +
    '\n' +
    '  (1) RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[2888,8,80,80] and type float on /job:localhost/replica:0/
task:0/device:GPU:0 by allocator GPU_0_bfc\n' +
    '\t [[{{function_node __inference__wrapped_model_219229856}}{{node model/transformer_encoder/encoder_layer/multi_head_atte
ntion/MatMul}}]]\n' +
    "Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptio
ns for current allocation info. This isn't available when running in Eager mode.\n" +
    '\n' +
    '0 successful operations.\n' +
    '0 derived errors ignored.',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
```

혹시 몰라 내용올리니 참고하시기 바라고, 위 알려주신대로 멀티라인으로 한번 해봐야겠습니다.

**Comment by gih2yun** [comment]
안녕하세요.
저희도 적당한 수준의 동시작업을 테스트해봤지만, 얼마까지 버티는지 부하 시험을 최대로 해보지는 못했는데요.

@ryuken73 님의 작업 결과를 보니, 나름 안심이 됩니다.

#### 위 오류에 대해서
- 위 오류는 텐서플루우 백엔드에서 발생한 오류이구요.
- 텐서플로우가 처리할 수 있는 한계를 넘어선 경우입니다.
- 말씀하신 것처럼, 어지간해서 서버는 죽지 않도록 해두었습니다.
- 엔터프라이즈 레벨에서 쓸 수 있는 수준입니다.

#### 응답 성능에 대해서
참고로 저희가 테스트해보니, 동시에 256개 정도 이상의 문장을 한꺼번에 보낼 때까지는 점진적으로 응답성능이 빨라집니다.
더 많이 보내도 응답 성능이 줄지는 않지만, 더 빨라지지는 않습니다.
즉, 512 문장을 보내면, 256 문장을 보낼때 보다 2배 더 걸립니다.

이런 것을 개선하는 작업도 계획에 잡혀있고, 내부 실험에서는 약 30% 이상 개선이 되는 것을 확인하기는 했습니다.
이것은 문서화되어 있지 않는 사항이니, 참고해주시면 좋겠습니다.

#### 동시 문장 호출시 주의할 사항

여러 개의 문장을 동시에 보낼 때, 저희가 자동으로 문장을 분할하게 되면, 문장의 개수가 늘어날 수도 있습니다. 이게 원하시는 결과가 아닐 수도 있습니다. 100번째 문장에 대한 처리 결과가 102번째에 나올 수도 있다는 얘기입니다.

https://docs.bareun.ai/howtouse/api-analyze/#_2

를 참고하셔서,  `auto_split_sentence`를 적당히 조정하시기 바랍니다.

참고로 여러 문장을 요청할 때, 문장의 응답 개수를 정확하게 보장해주는 API 버전은 추가로 개발 예정입니다.

**Comment by ryuken73** [comment]
안녕하세요. 상세한 가이드 감사드리고 멀티라인으로 진행한 결과 공유합니다.

확인해보니, 이미 데이터베이스에서 **멀티라인**인 **글**을 읽어서, **글**단위로 요청을 하고 있었습니다.
다만, 글들이 위에서 말씀하신 256문장보다는 작기 때문에 개선의 여지가 있을것으로 생각되어 여러개의 글을 모아 
한꺼번에 요청하는 식으로 진행을 해보았습니다. 아주 큰 성능향상은 없었지만 10%~20% 정도 속도 개선은 있었습니다.

한가지 더 질문드리고 싶은 것이 있는데요, 위처럼 여러개의 글을 모아서 보낸 요청에 대한 응답이 왔을 때, 
다시 개별 글의 결과로 나눌 수 있는 좋은 방법이 있을까 하는 겁니다.

각 데이터앞에 구분자를 넣는 방법으로 시도는 해 보았는데, 구분자도 형태소 분석이 되어 사용하기가 힘들었습니다.

예를 들면
```
  "나는 학교에 갑니다."
  "형태소 분석이 필요합니다"
```
를 아래처럼 "^^12345678^^" 구분자로 요청을 보냅니다.
```
 ^^12345678^^ 나는 학교에 갑니다.  ^^12345678^^ 형태소 분석이 필요합니다.
```
그리고 결과가 오면 "^^12345678^^"기준으로 응답을 나누려고 했는데 ^^12345678^^ 도 형태소
분석이 되 버리더군요.  사실 구분자가 형태소분석이 안되더라도 그리 좋은 방법은 아닌 것 같아서요.
문장을 합쳐서 보낸 요청의 응답을 합치기 전 개별 글 기준으로 나눌 수 있는 다른 좋은 방법이 있을까요?

그리고, 위 구분자를 고유명사로 사용자 사전에 등록해서 해봤는데, 예상한 결과로는 나오지 않더라구요.
(^^12345678^^ 이 고유명사 하나로 형태소분석이 될 것으로 생각했습니다.)

https://bareun.ai/demo/customDemo 에서도 확인해봤는데 역시 사용자사전 기반 결과로 나오지는 않더라구요.
뭔가 제가 잘못 이해하고 있는건지, 한번 확인해봐주시면 감사하겠습니다.
 
![image](https://user-images.githubusercontent.com/11531850/235403807-17d5847b-68b0-4b84-96ef-663152520e46.png)
![image](https://user-images.githubusercontent.com/11531850/235403949-99823441-a30c-44d3-8549-e44bcadc4c91.png)

**Comment by YugwonWon** [comment]
사용자 사전은 최근에 버그 수정이 완료되어 정상적으로 사용 가능합니다.
